import { pgTable, serial, text, timestamp, integer, real, index, jsonb } from "drizzle-orm/pg-core";

// Every row is scoped to an anonymous device ID generated by the app on first launch.
export const lures = pgTable(
  "lures",
  {
    id: serial().primaryKey(),
    deviceId: text("device_id").notNull(),
    name: text().notNull(),
    defaultPosition: text("default_position").notNull(),
    // Usual size you run this lure at (free text, e.g. 6", 10", 180mm). Optional.
    size: text(),
    // Hooks are optional — many anglers don't track them.
    hookSize: text("hook_size"),
    hookType: text("hook_type"),
    photoKey: text("photo_key"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("lures_device_idx").on(t.deviceId)],
);

export const strikes = pgTable(
  "strikes",
  {
    id: serial().primaryKey(),
    deviceId: text("device_id").notNull(),
    lureId: integer("lure_id")
      .notNull()
      .references(() => lures.id, { onDelete: "cascade" }),
    position: text().notNull(),
    outcome: text().notNull(),
    strikeDate: text("strike_date").notNull(),
    location: text().notNull().default(""),
    latitude: real(),
    longitude: real(),
    tempC: real("temp_c"),
    depthM: real("depth_m"),
    tide: text(),
    // Size of the lure run in this position for this strike, e.g. a 6" Dingo on the shotgun.
    lureSize: text("lure_size"),
    hookSize: text("hook_size"),
    hookType: text("hook_type"),
    photoKey: text("photo_key"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("strikes_device_idx").on(t.deviceId)],
);

// Spreads the angler has saved by name (e.g. "Marlin — shelf"), to load again on another day.
// `slots` holds each line's position, lure, size and hook exactly as set up on the boat.
export const spreads = pgTable(
  "spreads",
  {
    id: serial().primaryKey(),
    deviceId: text("device_id").notNull(),
    name: text().notNull(),
    slots: jsonb().notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [index("spreads_device_idx").on(t.deviceId)],
);
